export { default as BoxStatusCandidates } from './BoxStatusCandidates'
export { default as DeleteJobModal } from './DeleteJobModal'
export { default as GeneralInformationField } from './GeneralInformationField'
export { default as GeneralInformationHiring } from './GeneralInformationHiring'
export { default as HistoryLog } from './HistoryLog'
