import {
  STATUS_CANDIDATE,
} from 'shared/constants/constants'

export const ENABLED_CHANGE_STATUS = {
  [STATUS_CANDIDATE.APPLIED]: [
    STATUS_CANDIDATE.INTERVIEWING,
    STATUS_CANDIDATE.OFFERING,
    STATUS_CANDIDATE.KIV,
  ],
  [STATUS_CANDIDATE.INTERVIEWING]: [
    STATUS_CANDIDATE.OFFERING,
    STATUS_CANDIDATE.KIV,
  ],
  [STATUS_CANDIDATE.OFFERING]: [
    STATUS_CANDIDATE.HIRED,
    STATUS_CANDIDATE.OFFERED_LOST,
  ],
  [STATUS_CANDIDATE.HIRED]: [STATUS_CANDIDATE.EX_STAFTT],
  [STATUS_CANDIDATE.KIV]: [],
  [STATUS_CANDIDATE.OFFERED_LOST]: [],
  [STATUS_CANDIDATE.EX_STAFTT]: [],
}

export const OPENING_PAGE_APPLICATION = {
  list_candidate: 'ListCandidate',
  kanban: 'Kanban',
}
